version: '3.9'

secrets:
  token:
    file: /root/tgbotapi-framework-template/token

services:
  postgres:
    image: "postgres:15"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/

  app:
    image: ithersta/projects:tgbotapi-framework-template-staging
    restart: unless-stopped
    depends_on:
      - postgres
    secrets:
      - token
    environment:
      DATABASE_NAME: database
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_SERVER: postgres
      DUMP_USER_ID: 105293829
      TOKEN_FILE: /run/secrets/token

volumes:
  postgres:
