name: ktlint-format
on: workflow_dispatch
jobs:
  ktlint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Apply ktlint fixes
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessApply --continue
      - name: Commit fixes
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: stefanzweifel/git-auto-commit-action@v4
